# For all options see https://github.com/bbatsov/rubocop/tree/master/config

AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'

LineLength:
  Max: 90

MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 25

Style/BlockDelimiters:
  Enabled: false

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/DotPosition:
  EnforcedStyle: trailing

Style/MultilineBlockChain:
  Enabled: false

Style/MultilineMethodCallIndentation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

# When chaining functions enforcing an underscore can create extra visual noise
# that I'd rather avoid.
Lint/UnusedBlockArgument:
  Enabled: false
