source 'https://rubygems.org'

gem 'sinatra'
gem 'prius'
gem 'dotenv'
gem 'commander'
gem 'highline'
gem 'colorize'
gem 'pry-byebug'
gem 'rspec'
gem 'rubocop'
gem 'parser'
gem 'activesupport'
gem 'git'
gem 'hamster'
gem 'descriptive-statistics'
