source 'https://rubygems.org'
ruby '2.2.3'

gem 'hanami-router'
gem 'coach'
gem 'activerecord'
gem 'active_model_serializers'
gem 'pg'
gem 'rake'
gem 'prius'
gem 'dotenv'
gem 'commander'
gem 'highline'
gem 'colorize'
gem 'pry-byebug'
gem 'rubocop'
gem 'parser'
gem 'activesupport'
gem 'git'
gem 'descriptive-statistics'
gem 'que'
gem 'hamster'
gem 'jwt'
gem 'unirest'
gem 'octokit'
gem 'json-schema'
gem 'sshkey'
gem 'passenger'

group :development do
  gem 'rerun'
  gem 'capistrano'
  gem 'capistrano-bundler'
  gem 'capistrano-passenger'
  gem 'capistrano-rbenv'
end

group :test do
  gem 'rspec'
  gem 'rspec-its'
  gem 'database_cleaner'
  gem 'timecop'
  gem 'factory_girl'
  gem 'simplecov', require: false
end
